# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    services:
      nginx:
        image: redislabs:redistimeseries
        ports:
        - 6379:63769
          
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: PMD Check
      run: mvn pmd:check
    
    - name: validate code format
      run: mvn git-code-format:validate-code-format -Dgcf.globPattern=**/*
    
    - name: Test
      run: mvn integration-test 
    
    - name: Code coverage
      run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

